    chunks += [
        "Q: How to prevent prediabetes? A: Prediabetes can be prevented or reversed with healthy lifestyle changes such as adopting a Mediterranean diet, exercising regularly, losing excess weight, controlling blood pressure and cholesterol, limiting added sugars (less than 25–50 g/day depending on guidelines), and avoiding smoking.",
        "Q: What foods should I eat if I have prediabetes? A: Choose whole grains, lean protein, healthy fats, and nonstarchy vegetables. The ADA recommends filling half the plate with vegetables, one-quarter with healthy carbs, and one-quarter with lean protein. Water or zero-calorie drinks are preferred.",
        "Q: What foods should I avoid if I have prediabetes? A: Limit sugary beverages, cakes, cookies, and refined carbs like white bread, white rice, and white pasta. Avoid excess saturated and trans fats. Grapefruit and pomegranate juice may interact with medications, and high-dose supplements like ginseng, gingko, or garlic may cause low blood sugar.",
        "Q: What should I eat for breakfast if I have prediabetes? A: Opt for meals with lean protein, low-fat dairy, and fiber. Good options include high-fiber cereal (at least 5 g per serving), whole fruit, vegetables, and whole grains. If skipping breakfast, a low-carb meal replacement bar or shake may help.",
        "Q: What fruits should I avoid with prediabetes? A: All fruits are generally safe. Whole fresh fruit provides both fiber and natural sugar, which is healthier than fruit juice. However, avoid pomegranate and grapefruit juice if taking certain medications.",
        "Q: How much sugar is too much for people with prediabetes? A: WHO recommends less than 50 g (12 teaspoons) per day, ideally under 25 g (6 teaspoons). The AHA recommends less than 25 g for women and less than 36 g for men daily. A single soda can contains about 32 g (8 teaspoons), nearly a full day’s allowance.",
        "Q: Why is professional guidance important for prediabetes diet? A: Since prediabetes often coexists with other conditions like high cholesterol or high blood pressure, meal plans should be individualized. A doctor or dietitian can tailor diet and lifestyle strategies to each person’s health profile."
    ]
